on:
  push:
    branches:
      - prod


jobs:
  deploy:
    if: |
      (github.event_name == 'pull_request' && github.head_ref == 'master') ||
      (github.event_name == 'push' && github.ref == 'refs/heads/prod')

    runs-on: [self-hosted, Linux, X64]

    environment: production

    env:
      ENVIRONMENTAL_VARIABLES: ${{ vars.ENVIRONMENTAL_VARIABLES }}
      VAST_AI_API_KEY: ${{ secrets.VAST_AI_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: .

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install PM2
        run: echo '226044' | sudo -S npm install -g pm2

      - name: Running deployment script
        run: bash .github/scripts/deploy.sh

      - name: Echo the Environment variables
        run: echo "$ENVIRONMENTAL_VARIABLES"